// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace efc_web {
	
	
	public partial class LoginPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm messageform;
		
		protected System.Web.UI.WebControls.TextBox passwdbox;
		
		protected System.Web.UI.WebControls.Button loginbtn;
		
		protected System.Web.UI.WebControls.Button guestbtn;
		
		protected System.Web.UI.WebControls.Label outputbox;
	}
}
