// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace efc_web {
	
	
	public partial class MotorInterface {
		
		protected System.Web.UI.HtmlControls.HtmlForm messageform;
		
		protected System.Web.UI.WebControls.Button statusBtn;
		
		protected System.Web.UI.WebControls.Button startBtn;
		
		protected System.Web.UI.WebControls.Button stopBtn;
		
		protected System.Web.UI.WebControls.Button reverseBtn;
		
		protected System.Web.UI.WebControls.Button haltBtn;
		
		protected System.Web.UI.WebControls.Button resetBtn;
		
		protected System.Web.UI.WebControls.TextBox freqsetbox;
		
		protected System.Web.UI.WebControls.Button setFreq;
		
		protected System.Web.UI.WebControls.Button getFreq;
		
		protected System.Web.UI.WebControls.Label freqgetbox;
		
		protected System.Web.UI.WebControls.TextBox inputbox;
		
		protected System.Web.UI.WebControls.Button send;
		
		protected System.Web.UI.WebControls.Label outputbox;
	}
}
